<h1><center>Doolittle's Lower & Upper Decomposition Method</center></h1>

## Import These Required Modules.

In [13]:
import numpy as np
from scipy import linalg

A Is The Matrix.

In [14]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## In The Code Below :
<br>
P Is The Permutation Matrix Used To Resolve Singularity Issues.
<br>
L Is The Lower Triangular Matrix Of A.
<br>
Whereas U Is The Upper Triangular Matrix Of A.

**The Method scipy.linalg.lu(*arr*) Is Used To Decompose Matrix.**

In [16]:
P, L, U = linalg.lu(A)

In [17]:
print("P = ")
print(P)

P = 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## Below Are The Answers

In [18]:
print("L = ")
print(L)

L = 
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


In [19]:
print("U = ")
print(U)

U = 
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
